development:
  paypal_email: gilles_1238294519_biz@me.com
  paypal_secret: foobar
  paypal_cert_id: CFJPNL63J97XY
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/websrc"

test:
  paypal_email: test@example.com
  paypal_secret: testscret
  paypal_cert_id: 123456789
  paypal_url: testpaypalurl

# real production configuration
# production:
#   paypal_email: gillesmath@me.com
#   paypal_cert_id: Z5L63AE6WT2LN
#   paypal_url: "https://www.paypal.com/cgi-bin/websrc"

# testing production configuration
production:
  paypal_email: gilles_1238294519_biz@me.com
  paypal_secret: foobar
  paypal_cert_id: CFJPNL63J97XY
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/websrc"